added additional init for geth

diff --git a/charts/keth/charts/geth/templates/statefulset.yaml b/charts/keth/charts/geth/templates/statefulset.yaml
--- a/charts/keth/charts/geth/templates/statefulset.yaml
+++ b/charts/keth/charts/geth/templates/statefulset.yaml
@@ -524,6 +524,20 @@ spec:
       dnsPolicy: ClusterFirst
       initContainers:
         - args:
+            - init
+            - /root/.ethereum/genesis/genesis.json
+          image: ethereum/client-go:v1.10.1
+          imagePullPolicy: IfNotPresent
+          name: init-genesis
+          resources: {}
+          terminationMessagePath: /dev/termination-log
+          terminationMessagePolicy: File
+          volumeMounts:
+            - mountPath: /root/.ethereum
+              name: data
+            - mountPath: /root/.ethereum/genesis
+              name: config
+        - args:
             - -c
             - geth account import --password /root/.ethereum/account/accountSecret /root/.ethereum/account/accountPrivateKey || true
           command:
@@ -540,6 +554,40 @@ spec:
             - mountPath: /root/.ethereum/account
               name: account
               readOnly: true
+        {{ if .Values.global.bootnode.enabled -}}
+        - args:
+            - -c
+            - |
+              apk add --no-cache curl
+              CNT=0
+              echo "retrieving bootnodes from $(BOOTNODE_SVC)"
+              while [ $CNT -le 90 ]; do
+                curl -m 5 -s $(BOOTNODE_SVC) | xargs echo -n > /geth/bootnodes
+                if [ -s /geth/bootnodes ]; then
+                  cat /geth/bootnodes
+                  exit 0
+                fi
+                echo "no bootnodes found. retrying $CNT..."
+                sleep 2 || break
+                CNT=$((CNT+1))
+              done
+              echo "WARNING. unable to find bootnodes. continuing but geth may not be able to find any peers."
+              exit 0
+          command:
+            - /bin/sh
+          env:
+            - name: BOOTNODE_SVC
+              value: {{ template "bootnode.fullname" . }}
+          image: ethereum/client-go:v1.10.1
+          imagePullPolicy: IfNotPresent
+          name: get-bootnodes
+          resources: {}
+          terminationMessagePath: /dev/termination-log
+          terminationMessagePolicy: File
+          volumeMounts:
+            - mountPath: /geth
+              name: data
+        {{- end }}
       restartPolicy: Always
       schedulerName: default-scheduler
       securityContext: {}
